from __future__ import annotations
from sqlalchemy import CheckConstraint,Column,ForeignKey,Index,Integer,MetaData,String,Table,Text,func
metadata=MetaData()
companies=Table('companies',metadata,Column('id',Integer,primary_key=True),Column('name',String(255),nullable=False),Column('contact_email',String(320),nullable=False,server_default=''),Column('phone',String(80),nullable=False,server_default=''),Column('active',Integer,nullable=False,server_default='1'),Column('created_at',String(40),nullable=False),Column('base_currency',String(3),nullable=False,server_default='EUR'))
Index('uq_companies_name_ci',func.lower(companies.c.name),unique=True)
users=Table('users',metadata,Column('id',Integer,primary_key=True),Column('company_id',Integer,ForeignKey('companies.id')),Column('role',String(20),nullable=False),Column('first_name',String(120),nullable=False),Column('last_name',String(120),nullable=False),Column('email',String(320),nullable=False),Column('password_hash',Text,nullable=False),Column('active',Integer,nullable=False,server_default='1'),Column('created_at',String(40),nullable=False),CheckConstraint("role IN ('supervisor','operator','customer')",name='ck_users_role'))
Index('uq_users_email_ci',func.lower(users.c.email),unique=True)
sessions=Table('sessions',metadata,Column('token',String(128),primary_key=True),Column('user_id',Integer,ForeignKey('users.id'),nullable=False),Column('acting_company_id',Integer,ForeignKey('companies.id')),Column('csrf_token',String(128),nullable=False),Column('created_at',String(40),nullable=False),Column('expires_at',String(40),nullable=False))
audit_log=Table('audit_log',metadata,Column('id',Integer,primary_key=True),Column('company_id',Integer,ForeignKey('companies.id')),Column('actor_user_id',Integer,ForeignKey('users.id')),Column('actor_role',String(20)),Column('acting_company_id',Integer,ForeignKey('companies.id')),Column('action',String(120),nullable=False),Column('entity_type',String(120),nullable=False),Column('entity_id',String(120)),Column('before_json',Text),Column('after_json',Text),Column('created_at',String(40),nullable=False))
