from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "0002_setup_booking_foundation"
down_revision = "0001_core"
branch_labels = None
depends_on = None


def ci_unique(name: str, table: str, column: str, *extra: str) -> None:
    expressions = [sa.text(value) for value in extra] + [sa.text(f"lower({column})")]
    op.create_index(name, table, expressions, unique=True)


def upgrade() -> None:
    op.add_column("companies", sa.Column("base_currency", sa.String(3), nullable=False, server_default="EUR"))

    op.create_table("setup_elements", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("element_type", sa.String(255), nullable=False), sa.Column("pricing_method", sa.String(80), nullable=False), sa.Column("base_price", sa.Float, nullable=False, server_default="0"), sa.Column("active", sa.Integer, nullable=False, server_default="1"))
    ci_unique("uq_setup_elements_company_name_ci", "setup_elements", "name", "company_id")
    op.create_table("setup_person_types", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("short_name", sa.String(8), nullable=False, server_default=""), sa.Column("ask_age", sa.Integer, nullable=False, server_default="0"), sa.Column("active", sa.Integer, nullable=False, server_default="1"))
    ci_unique("uq_setup_person_types_company_name_ci", "setup_person_types", "name", "company_id")
    op.create_table("setup_addons", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("pricing_method", sa.String(80), nullable=False), sa.Column("ask_before_availability", sa.Integer, nullable=False, server_default="0"), sa.Column("item_kind", sa.String(20), nullable=False, server_default="Extra"), sa.Column("feature_group", sa.String(255), nullable=False, server_default=""), sa.Column("active", sa.Integer, nullable=False, server_default="1"))
    ci_unique("uq_setup_addons_company_name_ci", "setup_addons", "name", "company_id")
    op.create_table("setup_element_types", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("active", sa.Integer, nullable=False, server_default="1"))
    ci_unique("uq_setup_element_types_company_name_ci", "setup_element_types", "name", "company_id")
    op.create_table("setup_years", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("year", sa.Integer, primary_key=True), sa.Column("copied_from_year", sa.Integer))
    op.create_table("setup_seasons", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("year", sa.Integer, nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("start_date", sa.String(10), nullable=False), sa.Column("end_date", sa.String(10), nullable=False))
    ci_unique("uq_setup_seasons_company_year_name_ci", "setup_seasons", "name", "company_id", "year")
    op.create_table("setup_element_rates", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("year", sa.Integer, primary_key=True), sa.Column("element_id", sa.Integer, primary_key=True), sa.Column("season_id", sa.Integer, primary_key=True), sa.Column("rate", sa.Float, nullable=False))
    op.create_table("setup_occupancy", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("year", sa.Integer, primary_key=True), sa.Column("element_id", sa.Integer, primary_key=True), sa.Column("max_total", sa.Integer, nullable=False))
    op.create_table("setup_person_limits", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("year", sa.Integer, primary_key=True), sa.Column("element_id", sa.Integer, primary_key=True), sa.Column("person_type_id", sa.Integer, primary_key=True), sa.Column("max_count", sa.Integer, nullable=False))
    op.create_table("setup_type_addons", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("year", sa.Integer, primary_key=True), sa.Column("element_type", sa.String(255), primary_key=True), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("allowed", sa.Integer, nullable=False), sa.Column("min_qty", sa.Integer), sa.Column("max_qty", sa.Integer), sa.Column("rate", sa.Float))
    op.create_table("setup_element_addons", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("year", sa.Integer, primary_key=True), sa.Column("element_id", sa.Integer, primary_key=True), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("state", sa.String(1), nullable=False), sa.Column("min_qty", sa.Integer), sa.Column("max_qty", sa.Integer), sa.Column("rate", sa.Float), sa.CheckConstraint("state IN ('Y','N')", name="ck_setup_element_addons_state"))
    op.create_table("setup_person_prices", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("year", sa.Integer, primary_key=True), sa.Column("element_id", sa.Integer, primary_key=True), sa.Column("person_type_id", sa.Integer, primary_key=True), sa.Column("rate", sa.Float, nullable=False))

    op.create_table("user_menu_order", sa.Column("user_id", sa.Integer, primary_key=True), sa.Column("page_key", sa.String(120), primary_key=True), sa.Column("item_key", sa.String(120), primary_key=True), sa.Column("position", sa.Integer, nullable=False))
    op.create_table("setup_item_order", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("list_key", sa.String(120), primary_key=True), sa.Column("item_id", sa.Integer, primary_key=True), sa.Column("position", sa.Integer, nullable=False))
    op.create_table("setup_addon_when_options", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("option_code", sa.String(30), primary_key=True), sa.Column("label", sa.String(255), nullable=False), sa.Column("active", sa.Integer, nullable=False, server_default="1"), sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"), sa.CheckConstraint("option_code IN ('every_day','selected_days')", name="ck_addon_when_option"))
    op.create_table("setup_addon_person_pricing", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("pricing_mode", sa.String(30), nullable=False, server_default="single"), sa.CheckConstraint("pricing_mode IN ('single','person_type')", name="ck_addon_person_pricing_mode"))
    op.create_table("setup_addon_person_rates", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("year", sa.Integer, primary_key=True), sa.Column("person_type_id", sa.Integer, primary_key=True), sa.Column("rate", sa.Float, nullable=False))
    op.create_table("setup_element_popup_items", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("element_id", sa.Integer, primary_key=True), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("show_popup", sa.Integer, nullable=False, server_default="1"))

    op.create_table("customer_records", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("first_name", sa.String(120), nullable=False, server_default=""), sa.Column("last_name", sa.String(120), nullable=False, server_default=""), sa.Column("email", sa.String(320), nullable=False, server_default=""), sa.Column("phone", sa.String(80), nullable=False, server_default=""), sa.Column("address1", sa.String(255), nullable=False, server_default=""), sa.Column("address2", sa.String(255), nullable=False, server_default=""), sa.Column("postcode", sa.String(40), nullable=False, server_default=""), sa.Column("town", sa.String(120), nullable=False, server_default=""), sa.Column("country", sa.String(120), nullable=False, server_default=""), sa.Column("notes", sa.Text, nullable=False, server_default=""), sa.Column("active", sa.Integer, nullable=False, server_default="1"), sa.Column("created_at", sa.String(40), nullable=False), sa.Column("updated_at", sa.String(40), nullable=False))
    op.create_index("idx_customer_records_company", "customer_records", ["company_id", "active", "last_name", "first_name"])
    op.create_table("enquiries", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("customer_id", sa.Integer), sa.Column("status", sa.String(30), nullable=False, server_default="new"), sa.Column("source", sa.String(120), nullable=False, server_default=""), sa.Column("arrival_date", sa.String(10)), sa.Column("departure_date", sa.String(10)), sa.Column("party_size", sa.Integer), sa.Column("notes", sa.Text, nullable=False, server_default=""), sa.Column("workflow_status_id", sa.Integer), sa.Column("availability_expires_at", sa.String(40)), sa.Column("created_at", sa.String(40), nullable=False), sa.Column("updated_at", sa.String(40), nullable=False))
    op.create_table("enquiry_requests", sa.Column("enquiry_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("element_type", sa.String(255), nullable=False, server_default=""), sa.Column("element_id", sa.Integer), sa.Column("provisional_total", sa.Float), sa.Column("pricing_snapshot_json", sa.Text, nullable=False, server_default="{}"), sa.Column("updated_at", sa.String(40), nullable=False))
    op.create_table("enquiry_people", sa.Column("enquiry_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("person_type_id", sa.Integer, primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"))
    op.create_table("enquiry_addons", sa.Column("enquiry_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"))
    op.create_table("enquiry_addon_days", sa.Column("enquiry_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("service_date", sa.String(10), primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"))
    op.create_table("enquiry_addon_people", sa.Column("enquiry_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("person_type_id", sa.Integer, primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"))
    op.create_table("enquiry_addon_person_days", sa.Column("enquiry_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("person_type_id", sa.Integer, primary_key=True), sa.Column("service_date", sa.String(10), primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"))
    op.create_table("enquiry_selected_addons", sa.Column("enquiry_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"))

    op.create_table("offers", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("enquiry_id", sa.Integer), sa.Column("customer_id", sa.Integer), sa.Column("status", sa.String(30), nullable=False, server_default="draft"), sa.Column("valid_until", sa.String(10)), sa.Column("currency", sa.String(3), nullable=False, server_default="EUR"), sa.Column("total_amount", sa.Float, nullable=False, server_default="0"), sa.Column("pricing_snapshot_json", sa.Text, nullable=False, server_default="{}"), sa.Column("notes", sa.Text, nullable=False, server_default=""), sa.Column("created_at", sa.String(40), nullable=False), sa.Column("updated_at", sa.String(40), nullable=False))
    op.create_table("bookings", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("reference", sa.String(120), nullable=False), sa.Column("customer_id", sa.Integer), sa.Column("enquiry_id", sa.Integer), sa.Column("offer_id", sa.Integer), sa.Column("status", sa.String(30), nullable=False, server_default="provisional"), sa.Column("workflow_status_id", sa.Integer), sa.Column("arrival_date", sa.String(10), nullable=False), sa.Column("departure_date", sa.String(10), nullable=False), sa.Column("currency", sa.String(3), nullable=False, server_default="EUR"), sa.Column("total_amount", sa.Float, nullable=False, server_default="0"), sa.Column("pricing_snapshot_json", sa.Text, nullable=False, server_default="{}"), sa.Column("notes", sa.Text, nullable=False, server_default=""), sa.Column("created_at", sa.String(40), nullable=False), sa.Column("updated_at", sa.String(40), nullable=False), sa.UniqueConstraint("company_id", "reference", name="uq_bookings_company_reference"))
    op.create_table("booking_elements", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("booking_id", sa.Integer, nullable=False), sa.Column("element_id", sa.Integer, nullable=False), sa.Column("arrival_date", sa.String(10), nullable=False), sa.Column("departure_date", sa.String(10), nullable=False), sa.Column("pricing_method_snapshot", sa.String(80), nullable=False), sa.Column("unit_price_snapshot", sa.Float, nullable=False, server_default="0"), sa.Column("total_amount", sa.Float, nullable=False, server_default="0"), sa.Column("pricing_snapshot_json", sa.Text, nullable=False, server_default="{}"))
    op.create_table("booking_people", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("booking_element_id", sa.Integer, nullable=False), sa.Column("person_type_id", sa.Integer, nullable=False), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"), sa.Column("unit_price_snapshot", sa.Float, nullable=False, server_default="0"), sa.Column("total_amount", sa.Float, nullable=False, server_default="0"))
    op.create_table("booking_addons", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("booking_element_id", sa.Integer, nullable=False), sa.Column("addon_id", sa.Integer, nullable=False), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"), sa.Column("pricing_method_snapshot", sa.String(80), nullable=False), sa.Column("unit_price_snapshot", sa.Float, nullable=False, server_default="0"), sa.Column("total_amount", sa.Float, nullable=False, server_default="0"), sa.Column("rule_snapshot_json", sa.Text, nullable=False, server_default="{}"))
    op.create_table("booking_payments", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("booking_id", sa.Integer, nullable=False), sa.Column("amount", sa.Float, nullable=False), sa.Column("payment_date", sa.String(10), nullable=False), sa.Column("method", sa.String(80), nullable=False, server_default=""), sa.Column("reference", sa.String(120), nullable=False, server_default=""), sa.Column("notes", sa.Text, nullable=False, server_default=""), sa.Column("created_by_user_id", sa.Integer), sa.Column("created_at", sa.String(40), nullable=False))

    op.create_table("booking_status_definitions", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("short_name", sa.String(120), nullable=False, server_default=""), sa.Column("colour", sa.String(20), nullable=False, server_default="#F3C5C9"), sa.Column("display_order", sa.Integer, nullable=False, server_default="10"), sa.Column("internal_state", sa.String(30), nullable=False, server_default="CONFIRMED"), sa.Column("blocks_availability", sa.Integer, nullable=False, server_default="1"), sa.Column("expiry_minutes", sa.Integer), sa.Column("automation_config_json", sa.Text, nullable=False, server_default="{}"), sa.Column("active", sa.Integer, nullable=False, server_default="1"), sa.Column("created_at", sa.String(40), nullable=False), sa.Column("updated_at", sa.String(40), nullable=False))
    ci_unique("uq_booking_status_company_name_ci", "booking_status_definitions", "name", "company_id")

    op.create_table("element_closures", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("element_id", sa.Integer, nullable=False), sa.Column("start_date", sa.String(10), nullable=False), sa.Column("end_date", sa.String(10), nullable=False), sa.Column("reason", sa.Text, nullable=False, server_default=""), sa.Column("created_by_user_id", sa.Integer), sa.Column("created_at", sa.String(40), nullable=False), sa.Column("updated_at", sa.String(40), nullable=False))
    op.create_table("element_holds", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("element_id", sa.Integer, nullable=False), sa.Column("session_token", sa.String(128), nullable=False), sa.Column("holder_user_id", sa.Integer), sa.Column("arrival_date", sa.String(10), nullable=False), sa.Column("departure_date", sa.String(10), nullable=False), sa.Column("lead_name", sa.String(255), nullable=False, server_default=""), sa.Column("renewal_required_at", sa.String(40), nullable=False), sa.Column("expires_at", sa.String(40), nullable=False), sa.Column("created_at", sa.String(40), nullable=False), sa.Column("updated_at", sa.String(40), nullable=False), sa.UniqueConstraint("company_id", "element_id", "session_token", name="uq_element_hold"))
    op.create_table("company_hold_settings", sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("hold_seconds", sa.Integer, nullable=False, server_default="600"), sa.Column("grace_seconds", sa.Integer, nullable=False, server_default="60"), sa.Column("updated_by_user_id", sa.Integer), sa.Column("updated_at", sa.String(40), nullable=False))

    op.create_table("booking_requirement_sessions", sa.Column("session_token", sa.String(128), primary_key=True), sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("ready", sa.Integer, nullable=False, server_default="0"), sa.Column("arrival_date", sa.String(10), nullable=False, server_default=""), sa.Column("departure_date", sa.String(10), nullable=False, server_default=""), sa.Column("lead_name", sa.String(255), nullable=False, server_default=""), sa.Column("updated_at", sa.String(40), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.create_table("booking_requirement_people", sa.Column("session_token", sa.String(128), primary_key=True), sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("person_type_id", sa.Integer, primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"), sa.Column("ages_json", sa.Text, nullable=False, server_default="[]"))
    op.create_table("booking_requirement_addons", sa.Column("session_token", sa.String(128), primary_key=True), sa.Column("company_id", sa.Integer, primary_key=True), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"))
    op.create_table("hold_requirement_people", sa.Column("hold_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("person_type_id", sa.Integer, primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"), sa.Column("ages_json", sa.Text, nullable=False, server_default="[]"))
    op.create_table("hold_requirement_addons", sa.Column("hold_id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("addon_id", sa.Integer, primary_key=True), sa.Column("quantity", sa.Integer, nullable=False, server_default="0"))

    op.create_table("arrivals", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("booking_id", sa.Integer), sa.Column("customer_id", sa.Integer), sa.Column("arrival_type", sa.String(20), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="expected"), sa.Column("checkin_method", sa.String(20)), sa.Column("arrived_at", sa.String(40)), sa.Column("checked_in_at", sa.String(40)), sa.Column("notes", sa.Text, nullable=False, server_default=""), sa.Column("created_at", sa.String(40), nullable=False), sa.Column("updated_at", sa.String(40), nullable=False))
    op.create_table("self_checkin_tokens", sa.Column("id", sa.Integer, primary_key=True), sa.Column("company_id", sa.Integer, nullable=False), sa.Column("booking_id", sa.Integer, nullable=False), sa.Column("token", sa.String(128), nullable=False, unique=True), sa.Column("expires_at", sa.String(40), nullable=False), sa.Column("used_at", sa.String(40)), sa.Column("created_at", sa.String(40), nullable=False))
    op.create_table("web_schema_meta", sa.Column("key", sa.String(120), primary_key=True), sa.Column("value", sa.Text, nullable=False))


def downgrade() -> None:
    for table in reversed([
        "setup_elements","setup_person_types","setup_addons","setup_element_types","setup_years","setup_seasons","setup_element_rates","setup_occupancy","setup_person_limits","setup_type_addons","setup_element_addons","setup_person_prices","user_menu_order","setup_item_order","setup_addon_when_options","setup_addon_person_pricing","setup_addon_person_rates","setup_element_popup_items","customer_records","enquiries","enquiry_requests","enquiry_people","enquiry_addons","enquiry_addon_days","enquiry_addon_people","enquiry_addon_person_days","enquiry_selected_addons","offers","bookings","booking_elements","booking_people","booking_addons","booking_payments","booking_status_definitions","element_closures","element_holds","company_hold_settings","booking_requirement_sessions","booking_requirement_people","booking_requirement_addons","hold_requirement_people","hold_requirement_addons","arrivals","self_checkin_tokens","web_schema_meta"
    ]):
        op.drop_table(table)
    op.drop_column("companies", "base_currency")
